### ISSUE TITLE
Can call-api be used to build a full callcenter app?

### ISSUE THREAD

**Issue by MayamaTakeshi** [OpenSIPS/call-api#4]
Hi,
combining opensips.cfg with the call-api we implement a full call-center solution.
But I would like to see if it could be done using the call-api alone.
So:

1) how would we handle incoming calls using the call-api?
I mean, I can send the call to a sip endpoint where the call would be parked while routing decisions are made and start the processing from there.
But I was thinking if there is some way to do it purely within opensips.

2) what if we want to call multiple endpoints with CallStart? (like ringing a group in a call center?)

3) what if we want to do hunting of agents in a group serially (trying one sip endpoint after another).

About 2 and 3 I think the call-api is missing a way to create independent SIP dialogs not associated with a callee. 
Then after answer, we would do a CallBlindTransfer or CallHold etc (and for the legs that lost the hunt/ring race we would use CallEnd).

**Comment by razvancrainea** [comment]
`call-api` itself does not have a SIP stack, it only uses the JSON-RPC events triggered by OpenSIPS. Therefore it cannot handle incoming calls, nor implement any kind of SIP logic.
All the above can be implemented using OpenSIPS, that's where you should be working on.
